name: Node CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: NodeJS ${{ matrix.node-version }} on macOS
    runs-on: macos-15
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Environment Information
        run: |
          node --version
          npm --version

      - uses: github/codeql-action/init@v4
        with:
          tools: linked
          languages: javascript, actions
          queries: security-and-quality
          config: |
            paths-ignore:
              - coverage
              - node_modules

      - name: npm install and test
        run: npm cit
        env:
          CI: true

      - uses: github/codeql-action/analyze@v4
